name: UltimateMobCoins
main: nl.chimpgamer.ultimatemobcoins.paper.UltimateMobCoinsPlugin
version: ${version}
description: UltimateMobCoins plugin
api-version: '1.19'

softdepend:
  - PlaceholderAPI
  - MythicMobs
  - Vault
  - Oraxen
  - ItemsAdder
  - EcoMobs
  - BetonQuest
  - WorldGuard
  - MiniPlaceholders

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.9.23
  - org.jetbrains.kotlin:kotlin-reflect:1.9.23
  - org.jetbrains.exposed:exposed-core:0.48.0
  - org.jetbrains.exposed:exposed-dao:0.48.0
  - org.jetbrains.exposed:exposed-jdbc:0.48.0
  - org.xerial:sqlite-jdbc:3.43.0.0
  - org.mariadb.jdbc:mariadb-java-client:3.3.3
  - cloud.commandframework:cloud-paper:1.8.4
  - cloud.commandframework:cloud-minecraft-extras:1.8.4
  - cloud.commandframework:cloud-kotlin-coroutines:1.8.4
  - dev.dejvokep:boosted-yaml:1.3.1
  - io.github.rysefoxx.inventory:RyseInventory-Plugin:1.6.5
  - com.github.ben-manes.caffeine:caffeine:3.1.8