name: UltimateMobCoins
main: nl.chimpgamer.ultimatemobcoins.paper.UltimateMobCoinsPlugin
version: ${version}
description: UltimateMobCoins plugin
api-version: '1.19'

softdepend:
  - PlaceholderAPI
  - MythicMobs
  - Vault
  - Oraxen
  - ItemsAdder
  - EcoBosses

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.9.0
  - org.jetbrains.kotlin:kotlin-reflect:1.9.0
  - org.jetbrains.exposed:exposed-core:0.41.1
  - org.jetbrains.exposed:exposed-dao:0.41.1
  - org.jetbrains.exposed:exposed-jdbc:0.41.1
  - org.xerial:sqlite-jdbc:3.41.2.1
  - org.mariadb.jdbc:mariadb-java-client:3.1.4
  - cloud.commandframework:cloud-paper:1.8.3
  - cloud.commandframework:cloud-minecraft-extras:1.8.3
  - dev.dejvokep:boosted-yaml:1.3.1
  - io.github.rysefoxx.inventory:RyseInventory-Plugin:1.6.5