storage:
  type: SQLITE
  host: localhost
  port: 3306
  database: ultimatetags
  username: ultimatetags
  password: ultimatetags
  properties:
    useUnicode: true
    characterEncoding: utf8

mobcoins:
  disabled_worlds:
    - disabled_world

config-version: 1